targetScope = 'subscription'

@description('Azure region. Must support Azure AI Foundry Hub workspaces, Azure AI Services, and the chosen chat model. Safe defaults: eastus, eastus2, swedencentral, westus.')
param location string = 'eastus'

@description('Resource group name.')
param rgName string = 'insecure-llm-rg'

@description('Base name prefix for all resources (lowercase, no dashes).')
@minLength(3)
@maxLength(8)
param baseName string = 'illm'

@description('Username for the site-wide HTTP Basic Auth gate.')
param basicAuthUsername string = 'demo'

@description('Password for the site-wide HTTP Basic Auth gate. Generated by deploy.ps1 if not supplied.')
@secure()
param basicAuthPassword string

@description('Container image to deploy. On first run, leave as the public placeholder; the deploy script swaps it for the ACR image after `az acr build`.')
param containerImage string = 'mcr.microsoft.com/azuredocs/aci-helloworld:latest'

@description('Log Analytics retention in days. Minimum 30 on PerGB2018.')
@minValue(30)
@maxValue(730)
param logRetentionDays int = 30

@description('Maximum upload size in bytes enforced server-side. Default 10 MiB.')
param maxUploadBytes int = 10485760

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: rgName
  location: location
}

module resources './resources.bicep' = {
  name: 'insecure-llm-resources'
  scope: rg
  params: {
    location: location
    baseName: baseName
    basicAuthUsername: basicAuthUsername
    basicAuthPassword: basicAuthPassword
    containerImage: containerImage
    logRetentionDays: logRetentionDays
    maxUploadBytes: maxUploadBytes
  }
}

output rgName string = rg.name
output containerAppName string = resources.outputs.containerAppName
output containerAppFqdn string = resources.outputs.containerAppFqdn
output containerRegistryName string = resources.outputs.containerRegistryName
output containerRegistryLoginServer string = resources.outputs.containerRegistryLoginServer
output aiServicesName string = resources.outputs.aiServicesName
output foundryHubName string = resources.outputs.foundryHubName
output foundryProjectName string = resources.outputs.foundryProjectName
output foundryProjectConnectionString string = resources.outputs.foundryProjectConnectionString
output storageAccountName string = resources.outputs.storageAccountName
output searchServiceName string = resources.outputs.searchServiceName
output basicAuthUsername string = basicAuthUsername
